### ISSUE TITLE
line_names is longer than line_data

### ISSUE THREAD

**Issue by alejandroowen** [samtalki/yadi#9]
This is that the error looks like:
![image](https://github.com/samtalki/yadi/assets/69917992/8901e2c1-8e16-4d22-8b32-3ed9e16e7880)

To reproduce:
`import numpy as np`
`import opendssdirect as dss`
`import yadi.dss.model as dss_model`
`import yadi.dss.qsts as dss_qsts`

`cktfile = 'C:\\Users\\AlexO\\GitHub\\evacuationProject\\data\\OpenDSS Network\\v1.1\2016\\GSO\\urban-suburban\\scenarios\\base_timeseries\\opendss\\uhs20_1247.Master.dss'`
`qsts = dss_qsts.DSS_Timeseries(
    redirects=cktfile,
    time_step="15m",
    simulation_steps=24*4
    )`
`qsts.run()`

I suspect this has something to do with the fact that `len(qsts.dss.Lines.AllNames())` is greater than `len(qsts.get_line_data())`
In the function `get_line_data()` in `model.py` when `self.dss.Lines.Next()` is used to iterate through `line` it seems like sometimes the iterator skips a few elements. For example, if we do:

`line = qsts.dss.Lines.First()`
`for _ in range(14):`
`    print(line)`
`    line = qsts.dss.Lines.Next()`

We will get:

![image](https://github.com/samtalki/yadi/assets/69917992/f7671444-2102-4077-921e-4a7dbefef94b)

As you can see, the indexes 11 and 12 were skipped, which will cause an issue in `get_line_data()` that makes `len(qsts.dss.Lines.AllNames())` greater than `len(qsts.get_line_data())`, which I think will result in the initial error.

**Comment by samtalki** [comment]
This has been resolved by the most recent commit. The mismatch between line_names and the lines Iterator, I believe, is a low-level bug with OpenDSS. This has been resolved by iteratively extracting the line name in each iteration of the simulation. Note that the resulting line current time series matrix contains every single phase conductor, which is more than the number of lines. The line_data dictionary contains information about how many conductors each 3-phase line has.

The line currents example notebook has been updated to reflect these changes.

I have not been able to fully resolve this issue for the transformer currents at this time, so let us please hold off on that for now
